familyTree = {"name" : "First Generation Parents",
        "children" : [{"name" : "First Child",
                       "children" : [{"name" : "First Grand Child",
                                      "children" : [{"name" : "First Great Grand Child",
                                                     "children" : []},
                                                    {"name" : "Second Great Grand Child",
                                                     "children" : []}]},
                                     {"name" : "Second Grand Child",
                                      "children" : []},
                                     {"name" : "Third Grand Child",
                                      "children" : [{"name" : "First Great Grand Child",
                                                     "children" : []},
                                                    {"name" : "Second Great Grand Child",
                                                     "children" : [{"name" : "First Great Great Grand Child",
                                                                    "children" : []}]},
                                                    {"name" : "Third Great Grand Child",
                                                     "children" : []}]}]},
                      {"name": "Second Child",
                       "children" : [{"name" : "First Grand Child",
                                      "children" : []},
                                     {"name" : "Second Grand Child",
                                      "children" : [{"name" : "First Great Grand Child",
                                                     "children" : []},
                                                    {"name" : "Second Great Grand Child",
                                                     "children" : []},
                                                    {"name" : "Third Great Grand Child",
                                                     "children" : []}]},
                                     {"name" : "Third Grand Child",
                                      "children" : []}]},
                      {"name" : "Third Child",
                       "children" : [{"name" : "First Grand Child",
                                      "children" : [{"name" : "First Great Grand Child",
                                                     "children" : [{"name" : "First Great Great Grand Child",
                                                                    "children" : []}]}]},
                                     {"name" : "Second Grand Child",
                                      "children" : [{"name" : "First Great Grand Child",
                                                     "children" : []}]},
                                     {"name" : "Third Grand Child",
                                      "children" : []},
                                     {"name" : "Fourth Grand Child",
                                      "children" : [{"name" : "First Great Grand Child",
                                                     "children" : []},
                                                    {"name" : "Second Great Grand Child",
                                                     "children" : []}]}]},
                      {"name" : "Fouth Child",
                       "children" : []}]
        }

